### ISSUE TITLE
Make Git Submodule friendly 

### ISSUE THREAD

**Issue by BenjaminDSmithy** [getnamo/myo-ue4#1]
Hi there,
Would you consider going down a level in your repository and making https://github.com/getnamo/myo-ue4/tree/master/Plugins/MyoPlugin your root?

You can of course place your Readme.md file inside that folder and you can provide the outer binaries folder found here https://github.com/getnamo/myo-ue4/tree/master/Binaries as a ZIP file under each release.

This will allow developers who are working with Git as their project source control the ability to setup a Git Submodule for this plugin.

Example

Your .gitmodules file would look similar to this

```
[submodule "Plugins/MyoPlugin"]
    path = Plugins/MyoPlugin
    url = https://github.com/getnamo/myo-ue4.git
```

By doing this you allow a developer to contain the plugin in its own sub-repository and with that some ease of mind, as developers always stay up-to-date with the plugin for the branch they are on e.g. 4.3 automatically every time they Pull the project :smile:

**Comment by getnamo** [comment]
Hey, Thanks for championing this. Before I commit though I need to see how this would look like from the download end user.

I still believe the vast majority of use cases being drag and drop as such I don't want that case to be more complicated, nor should the ideal solution add the burden of creating two separate builds in the for each push.

Make a fork with a pull request of what you'd have in mind and I'll take a look and see how to best accommodate the two types of users (direct download and git).

**Comment by BenjaminDSmithy** [comment]
Sure thing :grinning:
I have just created a [Fork](https://github.com/BLOODTIDE12/MyoPlugin) and modified the repository as an example, however I feel I need to update the README.md file a bit more to explain the changes before doing a Pull Request.

I will look into finalizing it over the weekend.

My suggestion is to leave the master branch as is and the branches can accommodate those who wish to use a Git Submodule workflow.

It's a Win|Win that way :+1: 

I have also renamed my branch to MyoPlugin, as you will run into compile errors if the root folder name does not match that of the .uproject name. This is not a required change and can easily be mentioned in the README.md

if you have any further questions, don't hesitate to ask.

Cheers,
Benjamin

**Comment by BenjaminDSmithy** [comment]
Oh also I have created a GitHub Page which can be found here:
http://bloodtide12.github.io/MyoPlugin/

You can easily generate your own by going here:
https://github.com/getnamo/myo-ue4/settings

a GitHub Page will probably be handy for sharing on the UE4 Forums + Wiki for ease of use for those who want to download ASAP and not have to worry about getting setup with GitHub :sunglasses:

**Comment by getnamo** [comment]
For now the current structure is maintained for simplicity, if/when github release and push work as a single command, I'll revisit the issue.
